//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public string TeamCode { get; set; }
        public string TeamName { get; set; }
        public string IdeaTitle { get; set; }
        public string IdeaDescription { get; set; }
        public byte[] IdeaPptFile { get; set; }
    }
}
